name: dice
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

   uses-material-design: true
   assets:
     - images/dice_img1.png
     - images/dice_img2.png
     - images/dice_img3.png
     - images/dice_img4.png
     - images/dice_img5.png
     - images/dice_img6.png
